obstacle_range: 6.0
raytrace_range: 6.0

footprint: [[-0.21, 0.31], [0.215, 0.31], [0.363, 0], [0.215, -0.31], [-0.21, -0.31]]
footprint_padding: 0.01

inflation_radius: 1.5
cost_scaling_factor: 3.0

transform_tolerance: 0.5
map_type: costmap

observation_sources: scan realsense
scan: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true, expected_update_rate: 0.0}
realsense: {sensor_frame: realsense, data_type: LaserScan, topic: scan/realsense, marking: true, clearing: true, inf_is_valid: true, expected_update_rate: 0.0}